# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac344162512d55faafd70af15a31bc2760f0ba6aea331fca4e6d4545bc85109b615e98f5b674df0b8ad001f5807e8f6cf3be433c5e1aec8915b6d8e117021bf

test:
  secret_key_base: 709260ec21e18f0cf01acf47c760bbe43bf43e1ee880cdf4c5e8c25764ab949a3c6d5a2ed989680306be43007f2518d586a69eb9d6b8b96d79ed0b9636fc5630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
